const sampleUserData = [
    {
        username: "Saswati Das",
        user_id: "PCOS-2025-001",
        password: "password001",
        serial_number: 1,
        age: 23,
        weight: 62,
        height: 160,
        bmi: 24.2,
        cycle_length: 35,
        irregular_periods: true,
        acne: true,
        hair_growth: false,
        skin_darkening: true,
        bp_systolic: 120,
        bp_diastolic: 80,
        hb_count: 13.5,
        stress_level: "Moderate",
        physical_activity: "Low",
        pcos_prediction: "Medium Risk",
    },
    {
        username: "Ananya Roy",
        user_id: "PCOS-2025-002",
        password: "password002",
        serial_number: 2,
        age: 21,
        weight: 70,
        height: 158,
        bmi: 28.1,
        cycle_length: 40,
        irregular_periods: true,
        acne: false,
        hair_growth: true,
        skin_darkening: false,
        bp_systolic: 130,
        bp_diastolic: 85,
        hb_count: 12.8,
        stress_level: "High",
        physical_activity: "Low",
        pcos_prediction: "High Risk",
    },
    {
        username: "Ria Sharma",
        user_id: "PCOS-2025-003",
        password: "password003",
        serial_number: 3,
        age: 26,
        weight: 65,
        height: 162,
        bmi: 24.8,
        cycle_length: 30,
        irregular_periods: false,
        acne: true,
        hair_growth: false,
        skin_darkening: false,
        bp_systolic: 115,
        bp_diastolic: 75,
        hb_count: 13.0,
        stress_level: "Low",
        physical_activity: "Moderate",
        pcos_prediction: "Low Risk",
    },
    {
        username: "Priya Mehta",
        user_id: "PCOS-2025-004",
        password: "password004",
        serial_number: 4,
        age: 24,
        weight: 58,
        height: 165,
        bmi: 21.3,
        cycle_length: 30,
        irregular_periods: false,
        acne: false,
        hair_growth: true,
        skin_darkening: false,
        bp_systolic: 110,
        bp_diastolic: 70,
        hb_count: 13.8,
        stress_level: "Low",
        physical_activity: "High",
        pcos_prediction: "Low Risk",
    },
    {
        username: "Neha Kapoor",
        user_id: "PCOS-2025-005",
        password: "password005",
        serial_number: 5,
        age: 28,
        weight: 75,
        height: 160,
        bmi: 29.3,
        cycle_length: 40,
        irregular_periods: true,
        acne: true,
        hair_growth: false,
        skin_darkening: true,
        bp_systolic: 130,
        bp_diastolic: 85,
        hb_count: 12.5,
        stress_level: "High",
        physical_activity: "Low",
        pcos_prediction: "High Risk",
    },
    {
        username: "Sonali Sharma",
        user_id: "PCOS-2025-006",
        password: "password006",
        serial_number: 6,
        age: 22,
        weight: 68,
        height: 163,
        bmi: 25.6,
        cycle_length: 38,
        irregular_periods: true,
        acne: false,
        hair_growth: true,
        skin_darkening: false,
        bp_systolic: 120,
        bp_diastolic: 78,
        hb_count: 13.2,
        stress_level: "Moderate",
        physical_activity: "Low",
        pcos_prediction: "Medium Risk",
    },
    {
        username: "Divya Yadav",
        user_id: "PCOS-2025-007",
        password: "password007",
        serial_number: 7,
        age: 29,
        weight: 80,
        height: 155,
        bmi: 33.3,
        cycle_length: 45,
        irregular_periods: true,
        acne: true,
        hair_growth: false,
        skin_darkening: true,
        bp_systolic: 135,
        bp_diastolic: 88,
        hb_count: 11.9,
        stress_level: "High",
        physical_activity: "Low",
        pcos_prediction: "High Risk",
    },
    {
        username: "Aarti Patel",
        user_id: "PCOS-2025-008",
        password: "password008",
        serial_number: 8,
        age: 30,
        weight: 64,
        height: 170,
        bmi: 22.1,
        cycle_length: 32,
        irregular_periods: false,
        acne: false,
        hair_growth: true,
        skin_darkening: false,
        bp_systolic: 110,
        bp_diastolic: 70,
        hb_count: 13.6,
        stress_level: "Low",
        physical_activity: "Moderate",
        pcos_prediction: "Low Risk",
    },
    {
        username: "Sonia Gupta",
        user_id: "PCOS-2025-009",
        password: "password009",
        serial_number: 9,
        age: 32,
        weight: 78,
        height: 168,
        bmi: 27.6,
        cycle_length: 28,
        irregular_periods: false,
        acne: true,
        hair_growth: false,
        skin_darkening: true,
        bp_systolic: 125,
        bp_diastolic: 80,
        hb_count: 13.2,
        stress_level: "Moderate",
        physical_activity: "High",
        pcos_prediction: "Medium Risk",
    },
    {
        username: "Aisha Khan",
        user_id: "PCOS-2025-010",
        password: "password010",
        serial_number: 10,
        age: 27,
        weight: 63,
        height: 162,
        bmi: 24.0,
        cycle_length: 36,
        irregular_periods: false,
        acne: true,
        hair_growth: true,
        skin_darkening: false,
        bp_systolic: 118,
        bp_diastolic: 76,
        hb_count: 13.4,
        stress_level: "Low",
        physical_activity: "High",
        pcos_prediction: "Low Risk",
    },
    {
        username: "Kavita Soni",
        user_id: "PCOS-2025-011",
        password: "password011",
        serial_number: 11,
        age: 25,
        weight: 72,
        height: 160,
        bmi: 28.1,
        cycle_length: 32,
        irregular_periods: true,
        acne: true,
        hair_growth: false,
        skin_darkening: true,
        bp_systolic: 130,
        bp_diastolic: 85,
        hb_count: 12.7,
        stress_level: "Moderate",
        physical_activity: "Low",
        pcos_prediction: "High Risk",
    },
    {
        username: "Madhuri Reddy",
        user_id: "PCOS-2025-012",
        password: "password012",
        serial_number: 12,
        age: 24,
        weight: 66,
        height: 167,
        bmi: 23.6,
        cycle_length: 34,
        irregular_periods: true,
        acne: false,
        hair_growth: false,
        skin_darkening: true,
        bp_systolic: 125,
        bp_diastolic: 78,
        hb_count: 13.3,
        stress_level: "High",
        physical_activity: "Moderate",
        pcos_prediction: "Medium Risk",
    },
    {
        username: "Shreya Arora",
        user_id: "PCOS-2025-013",
        password: "password013",
        serial_number: 13,
        age: 26,
        weight: 68,
        height: 164,
        bmi: 25.3,
        cycle_length: 33,
        irregular_periods: false,
        acne: true,
        hair_growth: true,
        skin_darkening: false,
        bp_systolic: 119,
        bp_diastolic: 76,
        hb_count: 13.6,
        stress_level: "Low",
        physical_activity: "High",
        pcos_prediction: "Low Risk",
    },
    {
        username: "Tanvi Mehra",
        user_id: "PCOS-2025-014",
        password: "password014",
        serial_number: 14,
        age: 28,
        weight: 60,
        height: 161,
        bmi: 23.1,
        cycle_length: 37,
        irregular_periods: true,
        acne: false,
        hair_growth: true,
        skin_darkening: true,
        bp_systolic: 122,
        bp_diastolic: 82,
        hb_count: 13.0,
        stress_level: "Moderate",
        physical_activity: "Low",
        pcos_prediction: "Medium Risk",
    },
    {
        username: "Niharika Sood",
        user_id: "PCOS-2025-015",
        password: "password015",
        serial_number: 15,
        age: 30,
        weight: 70,
        height: 159,
        bmi: 27.7,
        cycle_length: 41,
        irregular_periods: true,
        acne: false,
        hair_growth: true,
        skin_darkening: false,
        bp_systolic: 134,
        bp_diastolic: 86,
        hb_count: 12.8,
        stress_level: "High",
        physical_activity: "Low",
        pcos_prediction: "High Risk",
    }
];

module.exports = {data:sampleUserData};



